### ISSUE TITLE
Camera List not working.

### ISSUE THREAD

**Issue by xamox** [morefigs/pymba#1]
Came across this and very interested in incorporating support into SimpleCV (http://simplecv.org).  We currently have support for the old PvAPI driver but I would like to update to handle VIMBA.

I have installed under windows, I have confirmed that VIMBA is installed correctly and I can view streaming images in real time through the VimbaViewer.

It appears trying to walk through the code the call just returns 0:

vimba._getCameraInfos()
the line:
numCameras = numFound.value

is 0.  I have a feeling this is coming from the driver not necessarily your software.  I am using a GigE camera for testing, unfortunately I have about 10 sitting around Manta & Mako, but no 1394 (firewire) based to confirm if GigE is the culprit.  Any ideas in solving this would be greatly appreciated as I would also like help port it to linux.  I'm also using a 64bit machine and using the 64bit driver.

**Comment by ahyunni** [comment]
Hi all, I am not sure whether here is the best place to seek for advice, but I want to hear about experiences with using Vimba driver for AVT cameras. Currently, I am using PvAPI with python wrappers, and I am considering to update to Vimba. I am not sure whether it is something worthwhile to do. I realized xamox also said he/she was using PvAPI driver, so I was wondering if you found anything particularly better after the update. Thanks! (Please let me know if this question is inappropriate here, if this is the case, I will remove the post right away).
