### ISSUE TITLE
simultaneous capturing with 2 cameras

### ISSUE THREAD

**Issue by jferch** [morefigs/pymba#14]
Hey guys, 

I'm trying to acquire simultaneous footage with two mantas using the precision time protocol supported by the cameras. I already got them to sync properly but am currently stuck getting the image data. Do you know a good way to handle the acquisition of two cameras? Would threading / dividing into two separate processes be a good idea? Any help is highly appreciated :). Thanks in advance.

Cheers

**Comment by morefigs** [comment]
Can't say I've tried that before, and I'm not aware of the precision time protocol, but in general threading is a good idea for asynchronous events. If your threads are CPU intensive then move onto multiple processes (assuming you have multiple cores).

**Comment by derricw** [comment]
I have done acquisition from two cameras and, like morefigs recommended, I found it easiest to just use two processes.  You can use the `subprocess` module for this.

**Comment by jferch** [comment]
Thanks for the replies. Would you mind sharing your code? That would save me some time :>

**Comment by jferch** [comment]
Nevermind I got it working!
