### ISSUE TITLE
python hang

### ISSUE THREAD

**Issue by jferch** [morefigs/pymba#23]
Hey everybody,

I'm experiencing some strange python crashes by running the example code, although it works a couple of times now and then (opencv_liveview_example). This is the error message is get: [error](http://pastebin.com/iznPZax1)

It seems that the camera gets found but as soon as I want to get a frame, it crashes. Any ideas? I'm running Vimba 1.4 on a 32-bit Win7 system with Anaconda2. I set the jumbo packets to 9014. Let me know if you need more information. Any help is highly appreciated :)

Cheers

**Comment by morefigs** [comment]
Should now be fixed, see https://github.com/morefigs/pymba/pull/27
