### ISSUE TITLE
Need camera for testing

### ISSUE THREAD

**Issue by morefigs** [morefigs/pymba#26]
I no longer have access to an AVT camera for code testing, which makes it harder to respond to issues, fix bugs, approve pull requests, etc. If anyone has a spare one lying around they could loan me please let me know.

**Comment by hstarmans** [comment]
I would contact Alied Vision Technologies directly and ask them if they have some camera laying around. Refer to your Python library and that AVT customers appreciate your work.

**Comment by mrkschnk** [comment]
Is this still the case?

**Comment by morefigs** [comment]
I do have shared access to one now, so I'd only ask for one if it's no hassle at all.

**Comment by morefigs** [comment]
A spare camera would still be useful.

**Comment by lonedevwolf** [comment]
i have a spare color camera, but i'm not sure how i would give you access to it ? do you have any ideas ?

**Comment by morefigs** [comment]
Only if you're happy posting it. No worries if not!
