### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by kthouz** [morefigs/pymba#42]
Does anybody know how to have this library work on OS X? 
It looks [there is no](https://www.alliedvision.com/en/products/software.html) Mac OS version for vimba that has been released yet.

I will appreciate any idea

Thanks

**Comment by morefigs** [comment]
Sorry, this is just a wrapper for Vimba, so if their SDK doesn't work on
mac then this won't either. If they did release a version for mac then it
shouldn't be hard to get pymba working on that.
