### ISSUE TITLE
Use ExposureAuto and GainAuto

### ISSUE THREAD

**Issue by PedroSilva0** [morefigs/pymba#68]
I would like to adapt the live display example to use AutoGain and AutoExposure in "Continuous" mode, but when I set those features to  "Continuous" the live display doesn't adapt to lighting changes. 
I would like to know if this is a limitation of Pymba or if I need to do extra modifications instead of only changing those two features values to "Continuous"?

**Comment by morefigs** [comment]
There are a few different parameters that can affect e.g. automatic gain, see page 64 and onwards here: https://www.alliedvision.com/fileadmin/content/documents/products/cameras/various/features/GigE_Features_Reference.pdf.

It's been a while, but you should be able to set those sorts of things by setting camera attributes.

**Comment by GavinJia** [comment]
I tried to set as below:
```
self.camera = self.vimba.getCamera(self.cameraIds[0])
self.camera.openCamera()
self.camera.AcquisitionMode = 'Continuous'
self.camera.ExposureAuto = 'Continuous'
```
Two situations were happened. Overexposure or underexposed.
I don't know why...
