### ISSUE TITLE
Unable to run gige vision mako camera...

### ISSUE THREAD

**Issue by chandanlal92** [morefigs/pymba#77]
I am getting following error if I run opencv_example.py

 camera0 = vimba.getCamera(cameraIds[0])
IndexError: list index out of range

and also test_camera.py

**Comment by chandanlal92** [comment]
Please help to configure mako-G 503 Gige Vision Camera using pympa....I am unable to connect the camera

**Comment by chandanlal92** [comment]
is there any changes to be done for Gige Vision Camera in the Code

**Comment by morefigs** [comment]
Are you calling `system.runFeatureCommand("GeVDiscoveryAllOnce")`?

**Comment by chandanlal92** [comment]
Yes I am calling system.runFeatureCommand("GeVDiscoveryAllOnce")

**Comment by morefigs** [comment]
Please try adding a few second wait (`time.sleep(10)`) after calling the above command to see if that helps.

**Comment by morefigs** [comment]
You could try Pymba v0.2.

**Comment by chandanlal92** [comment]
Tried both the versions with delay still not same error.

**Comment by chandanlal92** [comment]
For GigE Camera is there anyother thing that needs to be changed?

**Comment by morefigs** [comment]
Does the camera work if you open it in Vimba Viewer? 

https://github.com/morefigs/pymba/blob/master/examples/camera/list_camera_ids.py works for me with a GigE camera and Pymba v0.2.

Could you also try https://github.com/morefigs/pymba/blob/master/examples/interface/list_interface_ids.py to see if you can see an interface?

Also try running the above examples after opening the camera in Vimba Viewer.

**Comment by chandanlal92** [comment]
I am able to work with the camera and in vimba viewer but it is not being listed in the camera list in any of the interfaces like vimbaC,Vimba C++ and Pymba

**Comment by morefigs** [comment]
Did that help? Is this still an issue?

**Comment by chandanlal92** [comment]
No I still have the issue.It is not solved.

**Comment by chandanlal92** [comment]
What IP Config did you use Persistant or LLA?

**Comment by morefigs** [comment]
I imagine you don't ever want to be using LLA. DHCP is probably preferable for avoiding networking issues. I'm using DHCP.

**Comment by chandanlal92** [comment]
I am able to stream using pymba now. The problem got resolved once I removed firewall. Thank you for your support will let you if there is any issues in future.
