### ISSUE TITLE
How to get the cameras under different interface( multiple Ethernet port)?

### ISSUE THREAD

**Issue by ouyangkid** [morefigs/pymba#78]
I have more than one camera each under an Ethernet port, I don't find how to set the source interface when start the vimba.

**Comment by morefigs** [comment]
Can you successfully list the cameras? If so it should just be a matter of selecting the correct list index.

**Comment by ouyangkid** [comment]
@morefigs Thanks for your kind replay, we saved the problem by assigning each interface with different gateway.
