### ISSUE TITLE
License change question

### ISSUE THREAD

**Issue by adam-urbanczyk** [morefigs/pymba#82]
I noticed that this (very useful!) project changed license to the more restrictive GPL3. Any particular reason to do so?

**Comment by morefigs** [comment]
Pymba originally used a GPL license, but was changed briefly to an MIT license: https://github.com/morefigs/pymba/commits/master/LICENSE. It's now been changed back to GPL. Happy to discuss further via email if you have specific needs.

**Comment by adam-urbanczyk** [comment]
Do you have anything against using and developing the older version under the previous license, e.g. as  forked here https://github.com/adam-urbanczyk/pymba ?

**Comment by morefigs** [comment]
Not at all. But if you're using Python 3 then Pymba 0.3+ has had a few improvements. Is the license the only issue stopping you?

**Comment by adam-urbanczyk** [comment]
Thanks! Yes, indeed it is the license. BSD or MIT would be more optimal.

**Comment by morefigs** [comment]
OK, done.

**Comment by adam-urbanczyk** [comment]
Thanks a lot!
