### ISSUE TITLE
PYMBA_VERSION error

### ISSUE THREAD

**Issue by BenDavisson** [morefigs/pymba#99]
Hello,

Seems like I have made a mistake from following the README.md or maybe it needs an update?

After following installation instructions and attempting import in python... I try to run this code: 
-----------------------------------------
from pymba import Vimba, PYMBA_VERSION

print(PYMBA_VERSION)
print(Vimba.version())

-----------------------------------------
and receive an error:

Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PYMBA_VERSION'

If I remove the PYMBA_VERSION import everything runs correctly.  Did I miss a step?

**Comment by morefigs** [comment]
Oops, thanks, I've updated the readme now.
